### ISSUE TITLE
Support Telenet login

### ISSUE THREAD

**Issue by wardwygaerts** [add-ons/plugin.video.streamz#1]
Thanks for supporting Streamz!

I can logon with an account (e-mail address) which was created in Streamz. But I'm not able to logon with a Telenet username (which is working on the website and app). On the Streamz site you can choose to logon with an sperate Streams account or a Telenet account.

**Comment by michaelarnauts** [comment]
I have no Telenet account to test this with. Feel free to contact me if you want to help me with this.

**Comment by wardwygaerts** [comment]
I would like to help, but I'm afraid I can only test and deliver logs. I use the same Telenet account in the [Yelo addon](https://github.com/add-ons/plugin.video.yelo), maybe this can help.

**Comment by mediaminister** [comment]
I made a draft PR https://github.com/add-ons/plugin.video.streamz/pull/4 that probably adds support for Telenet-logins. I'm not sure it is fully functional as I don't have a Telenet subscription myself.

Please test the following package and provide a debug log if it fails.

[plugin.video.streamz-0.0.1-telenetlogin-b0c9a70.zip](https://github.com/add-ons/plugin.video.streamz/files/5250483/plugin.video.streamz-0.0.1-telenetlogin-b0c9a70.zip)

**Comment by wardwygaerts** [comment]
No luck so far. I don't know if I have the correct debug logs (enabled it in add-on)

(I removed user & password :) )
https://paste.sh/DUqdldLD#HRQtmyJtHeUoKUgQqlYPjGEN

**Comment by mediaminister** [comment]
Okay, there was a problem with a http post request on Windows.
This should work or give at least a different error:
[plugin.video.streamz-0.0.1-telenetlogin-f90fde0.zip](https://github.com/add-ons/plugin.video.streamz/files/5252109/plugin.video.streamz-0.0.1-telenetlogin-f90fde0.zip)

**Comment by wardwygaerts** [comment]
I removed the add-on completely and reinstalled your latest build, but not working.

https://paste.sh/swspQW1E#lNoU2_3wo8H1p2ygienfkAyi

**Comment by michaelarnauts** [comment]
@wardwygaerts 

And can you try with this version? You will need to check your settings again, or remove the addon completely first.

[plugin.video.streamz-0.0.1-telenetlogin-eba510e.zip](https://github.com/add-ons/plugin.video.streamz/files/5254629/plugin.video.streamz-0.0.1-telenetlogin-eba510e.zip)

**Comment by wardwygaerts** [comment]
Super! We have a winner! 👍 
Everything seems to work fine.
