### ISSUE TITLE
Playback of streams are failing

### ISSUE THREAD

**Issue by NofanTasi** [add-ons/plugin.video.streamz#22]
Login succeeds and users are listed and content is listed.
But, typically I get (on 2 CoreELEC boxes and one own built gentoo Kodi HTPC):
ERROR: AddOnLog: InputStream Adaptive: Download https://dcs-vod.apis.anvato.net/vod/p/https://dpp-anvato-live.akamaized.net/eu/vod/10000001/20/12/09/10217113/audio-3F4DA5EC738E3DFFD72E4B1C4EDCE5A2B2846724C73F9-init.mp4?hdntl=exp=1607747427~acl=/*~hmac=005a38e1d31dfe841e2a52db3eedd42b6c88b25372adc12edd11d3d6a7169aa6 failed with error: 400
These boxes run up to date Kodi 18 software
let me know how I can help
Thanks for plugin!

**Comment by michaelarnauts** [comment]
I was afraid this would happen... This is due to a change at the backend, the same happened at VTM Go last week.

See https://github.com/add-ons/plugin.video.vtm.go/issues/241 for a workaround.

**Comment by NofanTasi** [comment]
thanks for figuring out the fix for inputstream !

**Comment by michaelarnauts** [comment]
Builds with workaround:
* [plugin.video.streamz-1.0.2-manifest-proxy-ec41332.zip](https://github.com/add-ons/plugin.video.streamz/files/5747488/plugin.video.streamz-1.0.2-manifest-proxy-ec41332.zip)
* [plugin.video.streamz-1.0.2+matrix.1-manifest-proxy-ec41332.zip](https://github.com/add-ons/plugin.video.streamz/files/5747490/plugin.video.streamz-1.0.2%2Bmatrix.1-manifest-proxy-ec41332.zip)

**Comment by michaelarnauts** [comment]
@a1ad Can you test this?

**Comment by a1ad** [comment]
@michaelarnauts quick test on LibreELEC kodi 18 looks ok!

So i have a play account that correspond to streamz non plus. When i try to play a streamz+ movie i get a "streamz fout" wouldn't it be better to show some more info?

**Comment by michaelarnauts** [comment]
@a1ad It would, but I only have a Streamz+ account to test with, so I don't know how I can see if an item is playable or not. Are Streamz+ items also visible for you on the website and the app? I think it would make sense to hide items that are not in your subscription to keep the interface clean.

**Comment by a1ad** [comment]
@michaelarnauts yes they are visible. Thanks for making this awesome plugin btw.

**Comment by michaelarnauts** [comment]
I assume the website and mobile app display a message when you want to play something that isn't in your subscription asking you to upgrade then? Is there a way to see that they are not playable before you try to play them?

If you can provide me a debug-log when you play an unsupported item, i can modify the code to display a better message.

**Comment by a1ad** [comment]
![Screenshot_20201228-170404_Streamz](https://user-images.githubusercontent.com/29516835/103227491-c2c5d380-492e-11eb-9f15-f8f27d25d961.jpg)

I can see the move but no play butten
