### ISSUE TITLE
Telenet login broken?

### ISSUE THREAD

**Issue by a1ad** [add-ons/plugin.video.streamz#25]
I got error: 103, where can i find the relative log files?

Jwt token is null

In the wiki:
Note: Je hebt hiervoor een betalend abonnement nodig van Streamz, of een Play More of Yugo abbonement bij Telenet.

I have just a Play abbo, not a play more but i can access streamz just fine.

**Comment by michaelarnauts** [comment]
You are able to use Streams fine on it's website or trough the App? Error 105 indicates it can't extract an access_token somehow. The Kodi log should contain more information. Just make sure to enable debug logging in the expert settings of the addon. You can upload a Kodi log there also. Just make sure to enable debug logging before trying again and uploading a log.

**Comment by michaelarnauts** [comment]
I've modified the Readme and the wiki. You should also have access to streamz with a Play subscription.

**Comment by a1ad** [comment]
I think i know what the problem is. In the debug log i can see the following:

<p class="error input--error">Vul de beveiligingscontrole in om verder te gaan.</p>

So i opened a browser on the same device and behold... a extra google recaptcha is waiting for me at the telenet login...

So i logged in though the webbrowser and the plugin starting to work...

**Comment by michaelarnauts** [comment]
Do you still have the Kodi log? I could use it to better handle the error and display a message.

**Comment by a1ad** [comment]
https://pastebin.com/B6Cbpe7H

**Comment by a1ad** [comment]
I got the same problem on my libreelec box, there is no browser to solve the recaptcha. I tried to ssh in with the -D option and used it as socks proxy on my laptop but it wont work.

We need that manual token method..

**Comment by michaelarnauts** [comment]
@a1ad is it possible that you have tried multiple times with an incorrect password? I'm trying to figure out why you needed to enter the captcha. The page at https://www2.telenet.be/waaromcaptcha doesn't give any clue :)

**Comment by a1ad** [comment]
> @a1ad is it possible that you have tried multiple times with an incorrect password? I'm trying to figure out why you needed to enter the captcha. The page at https://www2.telenet.be/waaromcaptcha doesn't give any clue :)

Possible, don't remember :), maybe because the kodi stuff was behind a VPN provider?

**Comment by michaelarnauts** [comment]
Ooh, that's possible. You shouldn't use a VPN to access Telenet.

**Comment by a1ad** [comment]
For Telenet i don't ;-)

**Comment by michaelarnauts** [comment]
Unable to reproduce unfortunately.
