### ISSUE TITLE
Favorites list "My list" does not sync perfectly with the website

### ISSUE THREAD

**Issue by pl0ng** [add-ons/plugin.video.streamz#30]
Hi,

Using R-Pi 3b with latest OSMC software.
Streamz 1.0.2

The favorites list called 'My List' in Streamz is not synced fully with the list from the website. Only part of my favorites show up in the plugin.
From within the plugin I can add an item to My List without any issues, even though it's already listed on the website favorites list.

**Comment by michaelarnauts** [comment]
That's odd. Are you using the same profile on the website as in Kodi?

**Comment by pl0ng** [comment]
Yes, both are set to same profile.

**Comment by michaelarnauts** [comment]
@pl0ng I can't really reproduce this. Everything I add on the website immediately shows up when I open "My List" in the Add-on, and everything I add to "My List" (via the context menu in the Add-on) also shows up in the website. Can you indicate what programs you add are not visible in the Add-on?

Also, when you open debug logging, and you open "My List". What do you see after the line with `NOTICE: [plugin.video.streamz] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "GET /streamz/main/swimlane/my-list HTTP/1.1" 200 931`?

**Comment by pl0ng** [comment]
I get a proper response, with all the proper metadata listed.
2021-01-02 19:54:58.059 T:1178276064   DEBUG: [plugin.video.streamz] [resources.lib.streamz.util] Got response (status=200): {"id":".." ....
Specific shows that I added via the website, but were not listed in the plugin are: The Undoing, Red Light. Probably there's a few more, but I only checked the ones that are on the immediate watchlist. If you want me to list 'm all, please let me know.

**Comment by michaelarnauts** [comment]
@pl0ng 

Do you still see this issue?

I've tried adding The Undoing and Red Light to "My List" on the streamz website, and they showed up on the addon just fine.

Can you try with the latest version you can download here? https://github.com/add-ons/plugin.video.streamz/pull/43#issuecomment-997399122

**Comment by michaelarnauts** [comment]
Can't reproduce unfortunately.
