### ISSUE TITLE
Matrix install fails

### ISSUE THREAD

**Issue by rottweilerken** [add-ons/plugin.video.streamz#36]
If you want to install the addon on Matrix (Libreelec nightly build) you get the error:
dependency xbmc.python version 2.26 could not be satisfied

**Comment by michaelarnauts** [comment]
You are correct, the packaged zip on this GitHub page is incorrect, but you should be able to install this Add-on from the Kodi repository just fine.

**Comment by dagwieers** [comment]
Did you install the add-on from the official Kodi repository? (Search for add-ons, type Streamz and install)

If instead you installed it as a ZIP file from the GitHub repository, you have to clone it, run `make multizip` and install the zip which has `matrix` in the version name.

**Comment by michaelarnauts** [comment]
The packaged zip in https://github.com/add-ons/plugin.video.streamz/releases/tag/v1.0.5 has been corrected, but I suggest to install it through the official Kodi repository as @dagwieers described.

**Comment by michaelarnauts** [comment]
For completeness, the reason the v1.0.5 release for matrix wasn't modified was fixed in this issue: https://github.com/xbmc/kodi-addon-submitter/pull/20
