### ISSUE TITLE
Streamz doesn't start - check logfile error

### ISSUE THREAD

**Issue by keiem** [add-ons/plugin.video.streamz#39]
Hello,

I used the 1 month free code from Humo to check-out streamz.  So I installed the add-on on LE Leia (khadas vim 1).
I can't login, I get the error to check my log file.  So I did, before it crashes I see this error:

HTTPError: 402 Client Error: Payment Required for url: https://lfvp-api.dpgmedia.net/profiles?products=STREAMZ%2CSTREAMZ_KIDS

I don't know if this has something to do with it or with the fact it's due to the one month free action.

Nevertheless, here is the link to a part of the log, the actual log is 6MB, so I copied and pasted wath I thought was relevant/

https://pastebin.com/D1PWSSGS

If you need the complete log I can share it with wetransfer.

**Comment by keiem** [comment]
Michaël,

this worked, I can login now.  Thanks for the great work you guys do!

**Comment by michaelarnauts** [comment]
@keiem thanks for verifying! I'll make a 1.0.6 release today that has this fix.
