### ISSUE TITLE
Opening the app fails, probably related to the login proces

### ISSUE THREAD

**Issue by ValentijnDemeyer** [add-ons/plugin.video.streamz#42]
**Describe the bug**
The addon is no longer accessable when opening. A kodi popup is shown indicating an error and to check the log.

**To Reproduce**
1. install addon
2. provide login details
3.try to open the addon

**Logs**
https://1drv.ms/u/s!AkMu2QdhP46xkMcOc2ihq6C3bvEclA?e=cswffS

**System**
 - Addon version: Version 1.0.6 + matrix 1
 - Kodi version: 10.0.1
 - Inputstream adaptive version: 19.0.0.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec
 - Special Hardware (RPI / Vero4K+ / ...): RPI 4

**Comment by matti008** [comment]
Same error on RPI2 with LibreElec 9.2.8

**Comment by sadrov** [comment]
yep, same here unfortunately on RPI3 with LibreElec (not sure about the version)

**Comment by andrasj** [comment]
Same here,
Getting HTTP 404-error: "Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/authorize/idToken"
(both on CoreElec with Kodi 18, and on windows with Kodi 19 )

**Comment by sammyke007** [comment]
+1

**Comment by hanskenb** [comment]
+1

**Comment by sadrov** [comment]
Do you guys still have the same problem? It's still there in my setup. I'm logging in through a telenet login.

**Comment by matti008** [comment]
Yes still the same problem, also using a telenet login

**Comment by kdufourbe** [comment]
Same issue here, using regular login.

**Comment by kdufourbe** [comment]
[plugin.video.streamz] [resources.lib.service] 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/streamz/catalog?pageSize=2000

It seems that things are changed at the end of Streamz that broke this plugin.

**Comment by kdufourbe** [comment]
Looks like the catalog entrypoint is removed and the list of items now is also fetched by the storefronts entrypoint instead. I didn't reverse engineer the old entrypoint, so not sure about how the old requests / responses looked like.

**Comment by michaelarnauts** [comment]
I assume the same new login flow can be used as I did with VTM Go. The catalog-endpoint has also been removed, and a few features depended on this, they also have to be removed for this to work again.

See https://github.com/add-ons/plugin.video.vtm.go/pull/311

**Comment by andrasj** [comment]
I remember also having issues with the vtmgo-addon at the time the streams-addon failed, with similiar errors in the log. But I also remember I disabled some catalog option to get rid of errors in the log, and I also modified the json-files with the authentication tokens (for the vtmgo addon).
However, currently the vtmgo addon seems to work (v1.2.12 on leia), I failed to get streamz working by modifying tokens through json.
I see you're working on a PR for the streamz-addon as well, I can test if it works once there's a zip available (I never tried to build/create a kodi-addon myself...)

**Comment by michaelarnauts** [comment]
@andrasj I've just released a new version for the vtm go addon with the changes that make it work again.

You can find a zip for streamz with a simular change here: https://github.com/add-ons/plugin.video.streamz/pull/43#issuecomment-997399122

Feel free to try it out, and let me know if it works or not :)

**Comment by sadrov** [comment]
@michaelarnauts Hey Michael, I can confirm that it now works again flawlessly! Thanks so much!
