### ISSUE TITLE
Addon not starting since May 31st

### ISSUE THREAD

**Issue by on4bam** [add-ons/plugin.video.streamz#46]
**Describe the bug**

When starting the plug-in there's an error message (Streamz fout ) and the add-on closes. There's no way to get into the configuration screen or do anything else. Other add-ons work as usual.

**To Reproduce**
1. Start Streamz

**System**
 - Addon version:  1.1.0+Matrix.1
 - Kodi version:19.4
 - Inputstream adaptive version: inputstream.adaptive v19.0.1.1
 - Operating System ( LibreElec): 10.0.2
 - Special Hardware (RPI / Vero4K+ / ...): RPi 4B

Restored a backup from before Streamz was installed, Installed Streamz add-on, entered one-time code on another device and then add-on stops.

**Comment by michaelarnauts** [comment]
@on4bam can you try with these zips?

[plugin.video.streamz-1.1.0.zip](https://github.com/add-ons/plugin.video.streamz/files/8822617/plugin.video.streamz-1.1.0.zip)
[plugin.video.streamz-1.1.0+matrix.1.zip](https://github.com/add-ons/plugin.video.streamz/files/8822618/plugin.video.streamz-1.1.0%2Bmatrix.1.zip)

**Comment by on4bam** [comment]
Hi,

Just tried the new version, had to register a new device and then all worked as before. Just tried one of the items on my list and it played as expected.
Thanks for the very fast fix.
BTW, I only tried the Matrix version.

**Comment by michaelarnauts** [comment]
@on4bam Thanks for the update, I'll try to make a release today.
