### ISSUE TITLE
See https://github.com/add-ons/plugin.video.vtm.go/issues/366.  Same issue.  Just bump x-api to 14 and solved.

### ISSUE THREAD

**Issue by molano999** [add-ons/plugin.video.streamz#57]
**Describe the bug**

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

**System**
 - Addon version:
 - Kodi version:
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

**Comment by michaelarnauts** [comment]
This is fixed in https://github.com/add-ons/plugin.video.streamz/releases/tag/v1.1.3

Can you try this release?
