### ISSUE TITLE
Login details with differently formatted email address not accepted

### ISSUE THREAD

**Issue by pl0ng** [add-ons/plugin.video.streamz#7]
Hi,

Using release v0.0.1, on Vero4K.
Login provider: streamz
Email login is formatted as blaat+streamz at gmail dot com.

The addon doesn't accept the input. 
I've tried single and double quotes around the email address, to no luck.
Streamz website allows this specific email addy format, so I was thinking this issue is on the side of the addon.

TIA

**Comment by michaelarnauts** [comment]
Do you have relevant log lines? Please make sure to mask your username and password if they are in there.

**Comment by pl0ng** [comment]
Hi Michael,
This can be closed. Upon looking closer, I saw that my streamz addon settings.xml somehow had some gibberish on the line of my login. I editted it just fine from cli and all is running smooth now. Can't figure out why though that it didn't accept it as a normal input from the kodi gui at the start...

**Comment by michaelarnauts** [comment]
Feel free to reopen of you can reproduce the issue.
